"""add_relationship

Revision ID: c6f8a9e1e7da
Revises: 6ecc1e1c5c8e
Create Date: 2023-04-17 20:33:39.051631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f8a9e1e7da'
down_revision = '6ecc1e1c5c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activation_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_activationkeys_product_id', 'products', ['product_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activation_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=70), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
